apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  labels:
    app: weather-app
spec:
  replicas: 2  # Number of replicas
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: impulsleistung/weather-app:latest  # Your Docker image
        ports:
        - containerPort: 8000  # The port your app runs on
