apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 80  # The service port that you will use to access externally
    targetPort: 8000  # The application's internal port
  type: LoadBalancer
